# Generated by Django 4.2 on 2023-05-12 13:40

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='articles_images/'),
        ),
    ]
